services:
  twio-python:
    build:
      context: ./
      dockerfile: docker-config/python-server.dockerfile
      args:
        - DEBUG=${DEBUG}
        - TO_EMAIL=${TO_EMAIL}
        - EMAIL_HOST=${EMAIL_HOST}
        - EMAIL_HOST_USER=${EMAIL_HOST_USER}
        - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
        - DEFAULT_FROM_EMAIL=${DEFAULT_FROM_EMAIL}
        - GOOGLE_API_KEY=${GOOGLE_API_KEY}
        - DB_NAME=${DB_NAME}
        - DB_USER=${DB_USER}
        - DB_PW=${DB_PW}
        - DB_HOST=db
    links:
      - db:db
    volumes:
      - file-volume:/opt/twio_web/media
      - cache-volume:/opt/static
    restart: always

  twio-nginx:
    build:
      context: ./
      dockerfile: docker-config/nginx-server.dockerfile
    depends_on:
      - twio-python
    volumes:
      - file-volume:/opt/media
      - cache-volume:/opt/static
    restart: always

  db:
    image: mariadb:lts
    environment:
       - MARIADB_RANDOM_ROOT_PASSWORD=1
       - MARIADB_USER=${DB_USER}
       - MARIADB_PASSWORD=${DB_PW}
       - MARIADB_DATABASE=${DB_NAME}
    volumes:
      - db-volume:/var/lib/mysql
    restart: always

volumes:
  db-volume:
  file-volume:
  cache-volume:
