services:
  twio-dev-db:
    image: mariadb:lts
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
       - MARIADB_RANDOM_ROOT_PASSWORD=1
       - MARIADB_USER=twio
       - MARIADB_PASSWORD=twio
       - MARIADB_DATABASE=twio
    volumes:
      - dev-db-volume:/var/lib/mysql

volumes:
  dev-db-volume:
